### PR TITLE
Update end to end tests with snapshot

### PR DESCRIPTION
**Pull request by jasunde**
Updated end to end test for the new API found in version 2

# 📝 Summary of Changes

- Resolves [issue #115](https://github.com/surpher/PactSwift/issues/115) by updating end to end tests
- Makes use of inline snapshot testing

# ⚠️ Items of Note

- Not all features from previous version have been ported to version 2 yet. I left in several tests that are skipped and commented out, but can remove those if you prefer.
- Github shows inconsistent spacing in some files, but it looks consistent when I view it in XCode...

# 🧐🗒 Reviewer Notes

## 🔨 How To Test

Run the tests

### CODE REVIEW

**Comment by surpher** [comment]
> Github shows inconsistent spacing in some files, but it looks consistent when I view it in XCode...

That's most likely due to using tabs instead of spaces. As good as using tabs for whitespace sounds, it's a bit of a nightmare to keep it _pristine_. I'll be reconsidering this in the code style.

**Comment by jasunde** [comment]
> > Github shows inconsistent spacing in some files, but it looks consistent when I view it in XCode...
> 
> That's most likely due to using tabs instead of spaces. As good as using tabs for whitespace sounds, it's a bit of a nightmare to keep it _pristine_. I'll be reconsidering this in the code style.

Ahh... I've never worked on a project that prefers tabs. I'll see about cleaning that up

**Comment by surpher** [comment]
Don't worry about it... I'm not fussed about it (too much). Here's the background on why tabs instead of spaces:
https://github.com/surpher/PactSwift/blob/main/Documentation/ADRs/ADR-002-Coding_standard.md#indentation 
Especially the last paragraph.

**Comment by surpher** [comment]
I'm leaning towards merging this one with snapshots. Nice work though.

**Review by surpher — APPROVED** [review]
Great stuff! Thanks @jasunde for helping out. :saluting_face:

**Pull request merged**
