### PR TITLE
feature: Set the format using RandomUUID example generator

### PR DESCRIPTION
**Pull request by wacumov**
# 📝 Summary of Changes
This pull request resolves issue #70 by allowing to set the format of `RandomUUID` example generator.

# 🧐🗒 Reviewer Notes
Of course, I understand that this functionality should be covered by unit tests. But I'm not sure, to which test suite they should be added.

### CODE REVIEW

**Comment by surpher** [comment]
The unit tests should be added to [/Tests/ExampleGenerators/RandomUuidTests.swift](https://github.com/surpher/PactSwift/blob/main/Tests/ExampleGenerators/RandomUuidTests.swift).

But this is a bit more complex than just generating the format in `PactSwift`. The `pactffi` binary used in `PactSwiftMockServer` will need to expose the option for it and we'll need to pass this flag to it. I need to recompile the `pactffi` that exposes that interface first. It has been exposed [here](https://github.com/pact-foundation/pact-reference/commit/e2151800de9ec5760936003fd00da3ec95b94dd6).

The problem is, even if we generate a UUID in `PactSwift`, the `pactffi` re-generates it anyway and overwrites it with the default lowercased without dashes unless we pass the flag `RandomUUID.Format` to mock server. 

If you want to see this through, I'll first need to recompile `PactSwiftMockServer` to expose the interface for you to somehow pass to mock server the following flags:
- `.simple`
- `.lower-case-hyphenated`
- `.upper-case-hyphenated`
- `.urn`

**Comment by wacumov** [comment]
Thank you very much for such detailed explanation of the problem and providing guides! 
I definitely will try to complete this task even it turned out a bit more complex that I thought initially.

**Comment by surpher** [comment]
No problem. 
Don't forget to update the Objective-C interface so the ObjC can take the Format parameter. I would leave the existing one that handles default value and add a new interface that would take the Format Parameter. Check some of the other ExampleGenerator implementations for ideas.

**Comment by surpher** [comment]
Done with #82

**Pull request closed without merging**
